import { useEffect, useState } from 'react';
import { Link } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import type { RouteVisit } from '@/features/field/data';
import { AppHeader, Button, ClientCard, Icon, Page } from '@/features/field/ui';
import { useFieldSession } from '@/features/field/session';
import { api } from '@/services/api';
import { palette, radius } from '@/theme/tokens';

export default function HomeScreen() {
  const { ready, token, profile, selectedPortfolio, login, started, toggleJornada } = useFieldSession();
  const [route, setRoute] = useState<{ total: number; completed: number; items: RouteVisit[] }>();
  const [error, setError] = useState('');
  useEffect(() => { if (token && selectedPortfolio) api.route(token, selectedPortfolio.id_table).then((data) => setRoute({ total: data.summary.total, completed: data.summary.completed, items: data.items })).catch((cause) => setError(cause.message)); }, [token, selectedPortfolio]);
  if (!ready) return <Page><View style={styles.center}><ActivityIndicator color={palette.red}/></View></Page>;
  if (!token || !profile) return <Login onSubmit={login}/>;
  const next = route?.items.find((item) => !item.state.completed);
  return <Page><AppHeader/><ScrollView contentContainerStyle={styles.scroll}><Text style={styles.greeting}>Hola, {profile.name.split(' ')[0]}</Text><Text style={styles.subtitle}>{selectedPortfolio?.name || 'Sin cartera'} · Datos actualizados desde la cartera asignada</Text><View style={styles.shift}><Text style={styles.shiftTitle}>{started ? 'Jornada en curso' : 'Jornada lista para iniciar'}</Text><View style={styles.metrics}><Metric value={String(route?.total ?? '—')} label="Visitas asignadas"/><Metric value={String(route?.completed ?? '—')} label="Gestionadas"/></View><Button label={started ? 'Pausar jornada' : 'Iniciar jornada'} icon={started ? 'pause-circle-outline' : 'play-outline'} onPress={toggleJornada}/><Text style={styles.shiftHint}>La ubicación solo se habilitará durante la jornada operativa.</Text></View>{error ? <Message text={error}/> : !route ? <View style={styles.loading}><ActivityIndicator color={palette.red}/><Text>Cargando ruta asignada…</Text></View> : next ? <View style={styles.next}><Text style={styles.section}>Próxima visita</Text><ClientCard client={next}/></View> : <View style={styles.empty}><Icon name="checkmark-done-outline" size={30} color={palette.green}/><Text style={styles.emptyTitle}>No hay visitas pendientes</Text><Text style={styles.emptyText}>La ruta y sus estados se muestran según la hoja de ruta vigente.</Text></View>}<View style={styles.quickRow}><Quick icon="git-network-outline" title="Mi ruta" href="/route"/><Quick icon="search-outline" title="Consultar cliente" href="/search"/><Quick icon="time-outline" title="Historial" href="/history"/></View></ScrollView></Page>;
}
function Login({ onSubmit }: { onSubmit: (username: string, password: string) => Promise<void> }) { const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState(''); const submit=async()=>{setBusy(true);setError('');try{await onSubmit(username,password);}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible iniciar sesión.');}finally{setBusy(false);}};return <Page><View style={styles.login}><View style={styles.loginMark}><Text style={styles.loginMarkText}>GC</Text></View><Text style={styles.loginTitle}>GEOCAMPO</Text><Text style={styles.loginText}>Ingresa con las mismas credenciales autorizadas para el Sistema de Campo.</Text><TextInput value={username} onChangeText={setUsername} placeholder="Usuario" autoCapitalize="none" style={styles.input}/><TextInput value={password} onChangeText={setPassword} placeholder="Contraseña" secureTextEntry style={styles.input} onSubmitEditing={submit}/>{error ? <Message text={error}/> : null}<Button label={busy ? 'Validando…' : 'Ingresar'} icon="log-in-outline" onPress={busy ? undefined : submit}/><Text style={styles.loginFoot}>Uso interno autorizado · Información sensible protegida</Text></View></Page> }
function Metric({value,label}:{value:string;label:string}){return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>}; function Quick({icon,title,href}:{icon:any;title:string;href:any}){return <Link href={href} asChild><Pressable style={styles.quick}><Icon name={icon} color={palette.red}/><Text style={styles.quickText}>{title}</Text></Pressable></Link>}; function Message({text}:{text:string}){return <View style={styles.message}><Icon name="information-circle-outline" color={palette.amber}/><Text style={styles.messageText}>{text}</Text></View>};
const styles=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center'},scroll:{padding:20,gap:16,paddingBottom:30},greeting:{fontSize:31,fontWeight:'800',color:palette.ink,marginTop:4},subtitle:{fontSize:15,color:palette.muted,lineHeight:22},shift:{backgroundColor:palette.black,borderRadius:radius.lg,padding:20,gap:15},shiftTitle:{color:'#fff',fontSize:19,fontWeight:'800'},metrics:{flexDirection:'row',gap:26},metric:{gap:4},metricValue:{color:'#fff',fontSize:25,fontWeight:'800'},metricLabel:{color:'#C9C4BE',fontSize:13},shiftHint:{color:'#C9C4BE',fontSize:13,lineHeight:19},section:{fontSize:21,fontWeight:'800',color:palette.ink},next:{gap:10},loading:{minHeight:130,alignItems:'center',justifyContent:'center',gap:12},empty:{borderWidth:1.5,borderColor:palette.line,borderRadius:radius.lg,padding:22,alignItems:'center',gap:7},emptyTitle:{fontSize:18,fontWeight:'800',color:palette.ink},emptyText:{textAlign:'center',color:palette.muted,lineHeight:20},quickRow:{flexDirection:'row',gap:10},quick:{flex:1,minHeight:105,borderWidth:1.5,borderColor:palette.line,borderRadius:radius.md,padding:14,gap:9,justifyContent:'center'},quickText:{fontSize:14,fontWeight:'800',color:palette.ink},message:{backgroundColor:palette.amberSoft,borderRadius:14,padding:13,flexDirection:'row',gap:8,alignItems:'center'},messageText:{flex:1,color:palette.amber,fontSize:14,fontWeight:'700'},login:{flex:1,justifyContent:'center',padding:28,gap:14,maxWidth:500,width:'100%',alignSelf:'center'},loginMark:{height:72,width:72,borderRadius:22,backgroundColor:palette.red,alignItems:'center',justifyContent:'center'},loginMarkText:{color:'#fff',fontSize:25,fontWeight:'800'},loginTitle:{fontSize:31,fontWeight:'800',color:palette.ink},loginText:{color:palette.muted,fontSize:16,lineHeight:23,marginBottom:8},input:{height:57,borderRadius:15,borderWidth:1.5,borderColor:palette.line,backgroundColor:palette.surface,paddingHorizontal:16,fontSize:16,color:palette.ink},loginFoot:{color:palette.muted,textAlign:'center',fontSize:12,lineHeight:18,marginTop:4} });
