import { useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { RouteVisit } from '@/features/field/data';
import { AppHeader, ClientCard, Icon, Page } from '@/features/field/ui';
import { useFieldSession } from '@/features/field/session';
import { api } from '@/services/api';
import { palette, radius } from '@/theme/tokens';

export default function RouteScreen() { const {token,selectedPortfolio}=useFieldSession(); const [items,setItems]=useState<RouteVisit[]>([]); const [summary,setSummary]=useState<{total:number;completed:number}>(); const [error,setError]=useState(''); useEffect(()=>{if(token&&selectedPortfolio)api.route(token,selectedPortfolio.id_table).then(data=>{setItems(data.items);setSummary(data.summary);}).catch(cause=>setError(cause.message));},[token,selectedPortfolio]); return <Page><AppHeader/><ScrollView contentContainerStyle={styles.scroll}><Text style={styles.title}>Mi ruta</Text><Text style={styles.subtitle}>{selectedPortfolio?.name||'Cargando cartera…'}</Text><View style={styles.routeStatus}><View><Text style={styles.routeTitle}><Text style={styles.green}>● </Text>{summary ? `${summary.completed}/${summary.total} gestionadas`:'Cargando ruta'}</Text><Text style={styles.routeSub}>Hoja de ruta semanal vigente</Text></View><Icon name="git-network-outline" color="#fff" size={27}/></View>{error?<View style={styles.error}><Icon name="alert-circle-outline" color={palette.amber}/><Text style={styles.errorText}>{error}</Text></View>:!summary?<View style={styles.loading}><ActivityIndicator color={palette.red}/></View>:items.length===0?<View style={styles.empty}><Icon name="calendar-clear-outline" color={palette.green} size={30}/><Text style={styles.emptyTitle}>No tienes visitas asignadas</Text><Text style={styles.emptyText}>La información se lee directamente de tu hoja de ruta.</Text></View>:<><Text style={styles.section}>Visitas de hoy · {items.length}</Text>{items.map(item=><ClientCard key={`${item.identifier}-${item.route_detail_id}`} client={item}/>)}</>}</ScrollView></Page>; }
const styles=StyleSheet.create({scroll:{padding:20,gap:14,paddingBottom:30},title:{fontSize:30,fontWeight:'800',color:palette.ink},subtitle:{color:palette.muted,fontSize:15},routeStatus:{backgroundColor:palette.black,borderRadius:radius.lg,padding:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},routeTitle:{color:'#fff',fontSize:18,fontWeight:'800'},green:{color:'#16A055'},routeSub:{color:'#C9C4BE',fontSize:13,marginTop:5},section:{fontSize:20,fontWeight:'800',color:palette.ink,marginTop:4},loading:{minHeight:180,alignItems:'center',justifyContent:'center'},empty:{borderWidth:1.5,borderColor:palette.line,borderRadius:radius.lg,padding:26,gap:8,alignItems:'center'},emptyTitle:{fontSize:18,fontWeight:'800',color:palette.ink},emptyText:{color:palette.muted,textAlign:'center',lineHeight:20},error:{backgroundColor:palette.amberSoft,borderRadius:14,padding:14,flexDirection:'row',gap:8,alignItems:'center'},errorText:{color:palette.amber,fontWeight:'700',flex:1} });
