import { useMemo, useState } from 'react';
import { Link } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { clients, currency } from '@/features/field/data';
import { AppHeader, Icon, Page, Pill } from '@/features/field/ui';
import { palette, radius } from '@/theme/tokens';
export default function SearchScreen() {
  const [query, setQuery] = useState('');
  const results = useMemo(() => clients.filter((client) => `${client.name} ${client.document} ${client.address}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <Page><AppHeader/><ScrollView contentContainerStyle={styles.scroll}>
    <Text style={styles.title}>Consultar cliente</Text><Text style={styles.subtitle}>Busca por DNI, nombre, teléfono, código o dirección</Text>
    <View style={styles.input}><Icon name="search-outline" size={25}/><TextInput value={query} onChangeText={setQuery} placeholder="Ej. Rosa Mendoza" placeholderTextColor={palette.muted} style={styles.textInput}/>{query.length > 0 && <Pressable onPress={() => setQuery('')}><Icon name="close" size={22} color={palette.muted}/></Pressable>}</View>
    <View style={styles.filter}><Text style={styles.filterText}>Cartera: Todas</Text><Icon name="chevron-down" color="#fff"/></View>
    {query.length === 0 && <View style={styles.recent}><View style={styles.recentTitle}><Text style={styles.resultTitle}>Búsquedas recientes</Text><Text style={styles.clear}>Limpiar</Text></View>{clients.slice(0, 2).map((client) => <Link key={client.id} href={{ pathname: '/client/[id]', params: { id: client.id } }} asChild><Pressable style={styles.recentItem}><View style={styles.recentIcon}><Icon name="time-outline" color={palette.muted}/></View><View style={styles.recentInfo}><Text style={styles.recentName}>{client.name}</Text><Text style={styles.recentDoc}>{client.document} · SJL</Text></View><Text style={styles.recentDebt}>{currency(client.debt)}</Text></Pressable></Link>)}</View>}
    <Text style={styles.resultTitle}>{results.length} resultados <Text style={styles.inCartera}>en cartera asignada</Text></Text>
    {results.map((client) => <View key={client.id} style={styles.result}><View style={styles.resultTop}><Pill label={client.priority ?? client.risk} tone={client.priority ? 'red' : 'neutral'}/><Text style={styles.resultStatus}>{client.status}</Text></View><Text style={styles.name}>{client.name}</Text><Text style={styles.doc}>{client.document}</Text><Text style={styles.address}><Icon name="location-outline" size={17} color={palette.muted}/> {client.address}, SJL</Text><View style={styles.resultBottom}><Text style={styles.debt}>{currency(client.debt)} <Text style={styles.debtLabel}>deuda total</Text></Text><Link href={{ pathname: '/client/[id]', params: { id: client.id } }} asChild><Pressable style={styles.viewButton}><Text style={styles.viewText}>Ver ficha</Text></Pressable></Link></View></View>)}
    <View style={styles.protected}><Icon name="shield-checkmark-outline" color={palette.muted}/><Text style={styles.protectedText}>Los documentos se muestran parcialmente protegidos. Uso interno autorizado.</Text></View>
  </ScrollView></Page>;
}
const styles=StyleSheet.create({scroll:{padding:20,gap:15,paddingBottom:30},title:{fontSize:30,fontWeight:'800',color:palette.ink,marginTop:6},subtitle:{fontSize:16,color:palette.muted,lineHeight:23},input:{height:62,borderWidth:2,borderColor:palette.ink,borderRadius:20,paddingHorizontal:18,flexDirection:'row',alignItems:'center',gap:11,marginTop:6,backgroundColor:palette.surface},textInput:{flex:1,fontSize:17,color:palette.ink},filter:{backgroundColor:palette.black,borderRadius:15,paddingVertical:16,paddingHorizontal:20,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},filterText:{color:'#fff',fontWeight:'800',fontSize:16},recent:{gap:10},recentTitle:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},resultTitle:{fontSize:18,fontWeight:'800',color:palette.ink},clear:{fontSize:14,color:palette.muted,textDecorationLine:'underline',fontWeight:'700'},recentItem:{borderWidth:1.5,borderColor:palette.line,borderRadius:radius.md,padding:14,flexDirection:'row',alignItems:'center',gap:12},recentIcon:{width:42,height:42,borderRadius:12,backgroundColor:palette.soft,alignItems:'center',justifyContent:'center'},recentInfo:{flex:1},recentName:{fontSize:16,fontWeight:'800',color:palette.ink},recentDoc:{color:palette.muted,marginTop:3},recentDebt:{fontSize:17,fontWeight:'800',color:palette.ink},inCartera:{fontSize:14,fontWeight:'400',color:palette.muted},result:{borderWidth:1.5,borderColor:palette.line,borderRadius:radius.lg,padding:18,gap:9,backgroundColor:palette.surface},resultTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},resultStatus:{color:palette.muted,fontWeight:'700'},name:{fontSize:20,fontWeight:'800',color:palette.ink,marginTop:3},doc:{color:palette.muted,fontSize:15},address:{color:palette.muted,fontSize:15},resultBottom:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:8},debt:{fontSize:22,color:palette.ink,fontWeight:'800'},debtLabel:{fontSize:13,color:palette.muted,fontWeight:'400'},viewButton:{backgroundColor:palette.red,borderRadius:14,paddingHorizontal:18,paddingVertical:12},viewText:{color:'#fff',fontWeight:'800',fontSize:15},protected:{backgroundColor:palette.soft,borderRadius:radius.md,padding:16,flexDirection:'row',gap:10,alignItems:'flex-start'},protectedText:{color:palette.muted,fontSize:14,lineHeight:20,flex:1} });
