import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { BackHeader, Button, Icon, Page, Pill } from '@/features/field/ui';
import { useFieldSession } from '@/features/field/session';
import { api, type AddressCorrectionData } from '@/services/api';
import { palette, radius } from '@/theme/tokens';

export default function AddressCorrectionScreen() {
  const { id, idTable } = useLocalSearchParams<{ id: string; idTable: string }>(); const { token, selectedPortfolio, location, requestLocation } = useFieldSession(); const table = Number(idTable) || selectedPortfolio?.id_table;
  const [data, setData] = useState<AddressCorrectionData>(); const [address, setAddress] = useState(''); const [district, setDistrict] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { if (!token || !table || !id) return; setLoading(true); setError(''); try { const result = await api.addressCorrection(token, table, id); setData(result); setAddress(result.correction?.direccion_corregida || result.correction?.direccion_search || ''); setDistrict(result.correction?.distrito_corregido || result.assignment.district || ''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible preparar la corrección.'); } finally { setLoading(false); } }, [token, table, id]);
  useEffect(() => { const timer = setTimeout(() => { void load(); }, 0); return () => clearTimeout(timer); }, [load]);
  const save = async () => { if (!token || !table || !id) return; if (!address.trim()) return setError('Ingresa la dirección corregida.'); setSaving(true); setError(''); try { const result = await api.saveAddressCorrection(token, table, id, { correctedAddress: address.trim(), correctedDistrict: district.trim(), latitude: location?.latitude ?? null, longitude: location?.longitude ?? null }); Alert.alert('Dirección actualizada', result.message, [{ text: 'Entendido', onPress: () => router.back() }]); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible guardar la dirección.'); } finally { setSaving(false); } };
  return <Page><BackHeader title="Corregir dirección"/><ScrollView contentContainerStyle={styles.scroll}>{loading ? <View style={styles.loading}><ActivityIndicator color={palette.red}/></View> : <><Text style={styles.title}>Verificación del domicilio</Text><Text style={styles.subtitle}>La corrección queda asociada a tu asignación y conserva la dirección original para auditoría.</Text>{error ? <View style={styles.error}><Icon name="warning-outline" color={palette.amber}/><Text style={styles.errorText}>{error}</Text></View> : null}<View style={styles.card}><Text style={styles.section}>Dirección registrada</Text><Text style={styles.original}>{data?.assignment.address || 'No hay dirección registrada para esta cuenta.'}</Text>{data?.assignment.department || data?.assignment.province ? <Text style={styles.locationText}>{[data?.assignment.district, data?.assignment.province, data?.assignment.department].filter(Boolean).join(' · ')}</Text> : null}</View><View style={styles.card}><Text style={styles.section}>Nueva dirección</Text><Text style={styles.label}>Dirección corregida *</Text><TextInput value={address} onChangeText={setAddress} multiline placeholder="Escribe la dirección validada en campo" placeholderTextColor="#938B83" style={styles.addressInput}/><Text style={styles.label}>Distrito corregido</Text><TextInput value={district} onChangeText={setDistrict} placeholder="Distrito" placeholderTextColor="#938B83" style={styles.input}/></View><View style={[styles.gpsCard, location ? styles.gpsReady : styles.gpsPending]}><Icon name={location ? 'location' : 'location-outline'} color={location ? palette.green : palette.amber} size={24}/><View style={{ flex: 1 }}><Text style={styles.gpsTitle}>{location ? 'Ubicación lista para validar' : 'Validación GPS opcional'}</Text><Text style={styles.gpsText}>{location ? `Precisión aproximada: ${Math.round(location.accuracy || 0)} m` : 'Puedes guardar la corrección y validarla cuando estés en el domicilio.'}</Text></View><Pressable onPress={requestLocation} accessibilityLabel="Actualizar ubicación"><Text style={styles.gpsAction}>Actualizar</Text></Pressable></View>{data?.correction ? <View style={styles.previous}><Pill label={data.correction.validado ? 'Validada' : 'Pendiente de GPS'} tone={data.correction.validado ? 'green' : 'amber'}/><Text style={styles.previousText}>Existe una corrección anterior. Al guardar se conserva el historial y esta será la más reciente.</Text></View> : null}<Button label={saving ? 'Guardando dirección…' : 'Guardar corrección'} icon="checkmark-circle-outline" onPress={saving ? undefined : save}/></>}</ScrollView></Page>;
}
const styles = StyleSheet.create({ scroll: { padding: 20, gap: 14, paddingBottom: 32 }, loading: { minHeight: 300, alignItems: 'center', justifyContent: 'center' }, title: { color: palette.ink, fontSize: 27, fontWeight: '900' }, subtitle: { color: palette.muted, lineHeight: 21 }, error: { flexDirection: 'row', gap: 9, alignItems: 'center', borderRadius: 14, padding: 14, backgroundColor: palette.amberSoft }, errorText: { flex: 1, color: palette.amber, fontWeight: '700' }, card: { borderRadius: radius.lg, borderWidth: 1.5, borderColor: palette.line, padding: 15, gap: 8, backgroundColor: palette.surface }, section: { fontSize: 18, fontWeight: '900', color: palette.ink }, original: { color: palette.ink, fontSize: 16, lineHeight: 23 }, locationText: { color: palette.muted, lineHeight: 20 }, label: { color: palette.ink, fontWeight: '800', fontSize: 13, marginTop: 5 }, input: { minHeight: 52, borderWidth: 1.5, borderColor: palette.line, borderRadius: 14, paddingHorizontal: 14, color: palette.ink, fontSize: 16 }, addressInput: { minHeight: 102, borderWidth: 1.5, borderColor: palette.line, borderRadius: 14, padding: 14, color: palette.ink, fontSize: 16, textAlignVertical: 'top' }, gpsCard: { borderRadius: radius.lg, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 10 }, gpsReady: { backgroundColor: palette.greenSoft }, gpsPending: { backgroundColor: palette.amberSoft }, gpsTitle: { color: palette.ink, fontWeight: '900' }, gpsText: { color: palette.muted, fontSize: 13, lineHeight: 19, marginTop: 2 }, gpsAction: { color: palette.green, fontWeight: '900' }, previous: { borderWidth: 1, borderColor: palette.line, borderRadius: 14, padding: 14, gap: 8 }, previousText: { color: palette.muted, lineHeight: 20 } });
