import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';

import { Icon, Page } from '@/features/field/ui';
import { useFieldSession } from '@/features/field/session';
import { palette, radius } from '@/theme/tokens';

export default function SignInScreen() {
  const { login } = useFieldSession();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [visible, setVisible] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const submit = async () => {
    setBusy(true); setError('');
    try { await login(username, password); router.replace('/home'); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible iniciar sesión.'); }
    finally { setBusy(false); }
  };
  return <Page><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView style={styles.scrollView} contentContainerStyle={styles.scrollContent} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag"><View style={styles.loginContent}><View style={styles.hero}><View style={styles.brandMark}><Text style={styles.brandMarkText}>GC</Text></View><View style={styles.heroCopy}><Text style={styles.brand}>GEOCAMPO</Text><Text style={styles.company}>COBRANZAS PERÚ</Text></View></View><View style={styles.intro}><Text style={styles.title}>Tu jornada empieza aquí.</Text><Text style={styles.subtitle}>Consulta tu ruta, registra gestiones y mantén al equipo conectado de forma segura.</Text></View><View style={styles.card}><View style={styles.cardTop}><View style={styles.cardIcon}><Icon name="shield-checkmark-outline" color={palette.red} size={22}/></View><View><Text style={styles.cardTitle}>Acceso seguro</Text><Text style={styles.cardCaption}>Usa tus credenciales corporativas</Text></View></View><Text style={styles.label}>Usuario</Text><View style={styles.inputShell}><Icon name="person-outline" color={palette.muted}/><TextInput value={username} onChangeText={setUsername} placeholder="Ingresa tu usuario" placeholderTextColor="#938B83" autoCapitalize="none" autoCorrect={false} returnKeyType="next" style={styles.input}/></View><Text style={styles.label}>Contraseña</Text><View style={styles.inputShell}><Icon name="lock-closed-outline" color={palette.muted}/><TextInput value={password} onChangeText={setPassword} placeholder="Ingresa tu contraseña" placeholderTextColor="#938B83" secureTextEntry={!visible} onSubmitEditing={submit} returnKeyType="go" style={styles.input}/><Pressable hitSlop={10} onPress={() => setVisible((value) => !value)}><Icon name={visible ? 'eye-off-outline' : 'eye-outline'} color={palette.muted}/></Pressable></View>{error ? <View style={styles.error}><Icon name="alert-circle-outline" color={palette.red}/><Text style={styles.errorText}>{error}</Text></View> : null}<Pressable disabled={busy || !username || !password} onPress={submit} style={({ pressed }) => [styles.submit, (busy || !username || !password) && styles.pressed]}><Icon name="log-in-outline" color="#fff"/><Text style={styles.submitText}>{busy ? 'Validando acceso…' : 'Ingresar'}</Text></Pressable></View><View style={styles.footer}><Icon name="lock-closed-outline" size={17} color={palette.green}/><Text style={styles.footerText}>Uso interno autorizado · Información de clientes protegida</Text></View></View></ScrollView></KeyboardAvoidingView></Page>;
}
const styles = StyleSheet.create({ flex: { flex: 1 }, scrollView: { flex: 1, width: '100%' }, scrollContent: { flexGrow: 1, alignItems: 'center', paddingHorizontal: 20, paddingVertical: 24 }, loginContent: { width: '100%', maxWidth: 540, gap: 24 }, hero: { flexDirection: 'row', alignItems: 'center', gap: 14 }, brandMark: { height: 68, width: 68, borderRadius: 22, backgroundColor: palette.red, justifyContent: 'center', alignItems: 'center', shadowColor: palette.red, shadowOpacity: .22, shadowRadius: 12, elevation: 4 }, brandMarkText: { color: '#fff', fontSize: 24, fontWeight: '900' }, heroCopy: { gap: 2 }, brand: { color: palette.ink, fontSize: 25, fontWeight: '900', letterSpacing: -.5 }, company: { color: palette.muted, fontSize: 12, fontWeight: '800', letterSpacing: 1.4 }, intro: { gap: 8 }, title: { color: palette.ink, fontSize: 31, lineHeight: 37, fontWeight: '900', letterSpacing: -.7 }, subtitle: { color: palette.muted, fontSize: 16, lineHeight: 23 }, card: { backgroundColor: palette.surface, borderColor: palette.line, borderWidth: 1, borderRadius: 24, padding: 20, gap: 10, shadowColor: '#2B2520', shadowOpacity: .08, shadowRadius: 18, shadowOffset: { width: 0, height: 7 }, elevation: 3 }, cardTop: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 6 }, cardIcon: { height: 40, width: 40, borderRadius: 13, backgroundColor: palette.redSoft, justifyContent: 'center', alignItems: 'center' }, cardTitle: { color: palette.ink, fontWeight: '800', fontSize: 17 }, cardCaption: { color: palette.muted, fontSize: 12, marginTop: 2 }, label: { color: palette.ink, fontWeight: '800', fontSize: 13, marginTop: 3 }, inputShell: { minHeight: 55, paddingHorizontal: 14, borderRadius: 15, backgroundColor: '#FFFEFC', borderColor: palette.line, borderWidth: 1.5, alignItems: 'center', gap: 10, flexDirection: 'row' }, input: { flex: 1, minWidth: 0, fontSize: 16, color: palette.ink, paddingVertical: 0 }, error: { flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 12, backgroundColor: palette.redSoft, padding: 11, marginTop: 2 }, errorText: { flex: 1, color: palette.red, fontSize: 13, fontWeight: '700' }, submit: { minHeight: 54, borderRadius: 15, backgroundColor: palette.red, marginTop: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 }, submitText: { color: '#fff', fontSize: 16, fontWeight: '900' }, footer: { width: '100%', maxWidth: 540, flexDirection: 'row', alignItems: 'center', gap: 7, paddingBottom: 4 }, footerText: { color: palette.muted, fontSize: 12, lineHeight: 17, flex: 1 }, pressed: { opacity: .82 } });
