import { useEffect, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { Client } from '@/features/field/data';
import { BackHeader, Button, Page } from '@/features/field/ui';
import { useFieldSession } from '@/features/field/session';
import { api } from '@/services/api';
import { palette, radius } from '@/theme/tokens';
export default function ClientScreen(){const {id,idTable}=useLocalSearchParams<{id:string;idTable:string}>();const {token,selectedPortfolio}=useFieldSession();const [client,setClient]=useState<Client>();const [error,setError]=useState('');const table=Number(idTable)||selectedPortfolio?.id_table;useEffect(()=>{if(token&&table&&id)api.client(token,table,id).then(data=>setClient(data.item)).catch(cause=>setError(cause.message));},[token,table,id]);return <Page><BackHeader title="Ficha del cliente"/><ScrollView contentContainerStyle={styles.scroll}>{error?<Text style={styles.error}>{error}</Text>:!client?<View style={styles.loading}><ActivityIndicator color={palette.red}/></View>:<><Text style={styles.name}>{client.name}</Text><Text style={styles.doc}>{client.document||client.identifier}</Text><Text style={styles.portfolio}>{client.portfolio.name}</Text><Button label="Registrar gestión" icon="clipboard-outline" onPress={()=>router.push({pathname:'/management/[id]',params:{id:client.identifier,idTable:String(client.portfolio.idTable)}})}/><View style={styles.actions}><View style={styles.action}><Button label="Ver gestiones" variant="dark" icon="time-outline" onPress={()=>router.push({pathname:'/client/[id]/history',params:{id:client.identifier,idTable:String(client.portfolio.idTable)}})}/></View><View style={styles.action}><Button label="Corregir dirección" variant="outline" icon="location-outline" onPress={()=>router.push({pathname:'/client/[id]/address',params:{id:client.identifier,idTable:String(client.portfolio.idTable)}})}/></View></View><Text style={styles.section}>Información de la cuenta</Text><View style={styles.card}>{client.fields.map(field=><View key={field.field} style={styles.row}><Text style={styles.label}>{field.header}</Text><Text style={styles.value}>{String(field.value||'—')}</Text></View>)}</View></>}</ScrollView></Page>}
const styles=StyleSheet.create({scroll:{padding:20,gap:12,paddingBottom:30},loading:{minHeight:300,justifyContent:'center',alignItems:'center'},name:{fontSize:27,fontWeight:'800',color:palette.ink},doc:{fontSize:16,color:palette.muted},portfolio:{fontSize:14,color:palette.red,fontWeight:'700'},actions:{gap:10},action:{},section:{fontSize:20,fontWeight:'800',color:palette.ink,marginTop:6},card:{borderWidth:1.5,borderColor:palette.line,borderRadius:radius.md,overflow:'hidden'},row:{padding:14,borderBottomWidth:1,borderColor:palette.line,gap:5},label:{fontSize:13,color:palette.muted},value:{fontSize:16,color:palette.ink,fontWeight:'700'},error:{color:palette.amber,backgroundColor:palette.amberSoft,padding:14,borderRadius:12} });
