import { useEffect, useState } from 'react';
import { Link, Redirect } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import type { RouteVisit } from '@/features/field/data';
import { AppHeader, Button, ClientCard, Icon, Page } from '@/features/field/ui';
import { useFieldSession } from '@/features/field/session';
import { api } from '@/services/api';
import { palette, radius } from '@/theme/tokens';
import { FieldMap } from '@/features/field/map';
import { socketUrl, type Advisor } from '@/services/api';
import { io } from 'socket.io-client';

export default function HomeScreen() {
  const { ready, token, profile, selectedPortfolio, started, toggleJornada, location, online, locationError, requestLocation } = useFieldSession();
  const [route, setRoute] = useState<{ total: number; completed: number; items: RouteVisit[] }>();
  const [advisors, setAdvisors] = useState<Advisor[]>([]);
  const [error, setError] = useState('');
  useEffect(() => { if (token && selectedPortfolio && !profile?.isSupervisor) api.route(token, selectedPortfolio.id_table).then((data) => setRoute({ total: data.summary.total, completed: data.summary.completed, items: data.items })).catch((cause) => setError(cause.message)); }, [token, selectedPortfolio, profile?.isSupervisor]);
  useEffect(() => {
    if (!token || !selectedPortfolio || !profile?.isSupervisor) { const timer = setTimeout(() => setAdvisors([]), 0); return () => clearTimeout(timer); }
    let mounted = true;
    const loadAdvisors = () => api.advisors(token, selectedPortfolio.id_cartera)
      .then((data) => { if (mounted) { setAdvisors(data.items); setError(''); } })
      .catch((cause) => { if (mounted) setError(cause.message); });
    loadAdvisors();
    const interval = setInterval(loadAdvisors, 15_000);
    return () => { mounted = false; clearInterval(interval); };
  }, [token, selectedPortfolio, profile?.isSupervisor]);
  useEffect(() => {
    if (!token || !selectedPortfolio || !profile?.isSupervisor) return;
    const socket = io(socketUrl, { auth: { token }, transports: ['websocket'] });
    socket.on('location:update', (event: { advisorId: number; idCartera: number; latitude: number; longitude: number }) => {
      if (event.idCartera !== selectedPortfolio.id_cartera) return;
      setAdvisors((current) => current.map((advisor) => advisor.id === event.advisorId ? { ...advisor, latitude: event.latitude, longitude: event.longitude, live: true, location_source: 'Ubicación en jornada' } : advisor));
    });
    socket.on('location:inactive', (event: { advisorId: number; idCartera: number }) => {
      if (event.idCartera !== selectedPortfolio.id_cartera) return;
      setAdvisors((current) => current.map((advisor) => advisor.id === event.advisorId ? { ...advisor, live: false } : advisor));
    });
    return () => { socket.disconnect(); };
  }, [token, selectedPortfolio, profile?.isSupervisor]);
  if (!ready) return <Page><View style={styles.center}><ActivityIndicator color={palette.red}/></View></Page>;
  if (!token || !profile) return <Redirect href="/sign-in"/>;
  const next = route?.items.find((item) => !item.state.completed);
  if (profile.isSupervisor) return <Page><AppHeader/><ScrollView contentContainerStyle={styles.scroll}><Text style={styles.greeting}>Panel de supervisión</Text><Text style={styles.subtitle}>{selectedPortfolio?.name || 'Selecciona una cartera'} · se actualiza cada 15 s</Text><View style={styles.supervisorMetrics}><Metric inverted value={String(advisors.length)} label="Gestores asignados"/><Metric inverted value={String(advisors.filter((item) => item.latitude !== null).length)} label="Con última ubicación"/><Metric inverted value={String(advisors.reduce((sum, item) => sum + item.managed_today, 0))} label="Gestiones hoy"/></View><FieldMap location={null} title="Ubicaciones reportadas por el equipo" points={advisors.filter((item): item is Advisor & { latitude: number; longitude: number } => item.latitude !== null && item.longitude !== null).map((item) => ({ id: item.id, name: item.name, latitude: item.latitude, longitude: item.longitude, detail: item.location_source || undefined }))}/>{error ? <Message text={error}/> : null}<Text style={styles.section}>Gestores</Text>{advisors.length ? advisors.map((item) => <View style={styles.advisor} key={item.id}><View style={styles.advisorAvatar}><Text style={styles.advisorInitial}>{item.name.split(' ').map((part) => part[0]).slice(0,2).join('')}</Text></View><View style={{flex:1,minWidth:0}}><Text numberOfLines={2} style={styles.advisorName}>{item.name}</Text><Text numberOfLines={1} style={styles.advisorDetail}>{item.managed_today} gestiones hoy · {item.assigned} asignadas</Text></View><View style={[styles.locationState, item.live ? styles.locationReported : styles.locationMissing]}><Text style={styles.locationStateText}>{item.live ? 'En jornada' : item.latitude !== null ? 'Último reporte' : 'Sin reporte'}</Text></View></View>) : <View style={styles.empty}><Text style={styles.emptyTitle}>No hay gestores para esta cartera</Text><Text style={styles.emptyText}>El panel solo muestra gestores activos asociados a la cartera seleccionada.</Text></View>}<Text style={styles.disclaimer}>Las ubicaciones corresponden a reportes de jornada o a la última gestión registrada. La ruta semanal es definida por cada gestor.</Text></ScrollView></Page>;
  return <Page><AppHeader/><ScrollView contentContainerStyle={styles.scroll}><Text style={styles.greeting}>Hola, {profile.name.split(' ')[0]}</Text><Text style={styles.subtitle}>{selectedPortfolio?.name || 'Sin cartera'} · Datos actualizados desde la cartera asignada</Text><View style={styles.shift}><Text style={styles.shiftTitle}>{started ? 'Jornada en curso' : 'Jornada lista para iniciar'}</Text><View style={styles.metrics}><Metric value={String(route?.total ?? '—')} label="Visitas asignadas"/><Metric value={String(route?.completed ?? '—')} label="Gestionadas"/></View><Button label={started ? 'Pausar jornada' : 'Iniciar jornada'} icon={started ? 'pause-circle-outline' : 'play-outline'} onPress={toggleJornada}/><Text style={styles.shiftHint}>{location ? `GPS ${Math.round(location.accuracy || 0)} m · ${online ? 'conectado' : 'sin conexión'}` : locationError || 'La ubicación solo se habilitará durante la jornada operativa.'}</Text></View>{started ? <FieldMap title="Tu ubicación actual" location={location}/> : <Pressable onPress={requestLocation} style={styles.gpsRequest}><Icon name="locate-outline" color={palette.green}/><View style={{flex:1}}><Text style={styles.gpsRequestTitle}>Verificar GPS</Text><Text style={styles.gpsRequestText}>Solicita la ubicación antes de iniciar tu jornada.</Text></View><Icon name="chevron-forward" color={palette.muted}/></Pressable>}{error ? <Message text={error}/> : !route ? <View style={styles.loading}><ActivityIndicator color={palette.red}/><Text>Cargando ruta asignada…</Text></View> : next ? <View style={styles.next}><Text style={styles.section}>Próxima visita</Text><ClientCard client={next}/></View> : <View style={styles.empty}><Icon name="checkmark-done-outline" size={30} color={palette.green}/><Text style={styles.emptyTitle}>No hay visitas pendientes</Text><Text style={styles.emptyText}>La ruta y sus estados se muestran según la hoja de ruta vigente.</Text></View>}<View style={styles.quickRow}><Quick icon="git-network-outline" title="Mi ruta" href="/route"/><Quick icon="search-outline" title="Consultar cliente" href="/search"/><Quick icon="time-outline" title="Historial" href="/history"/></View></ScrollView></Page>;
}
function Metric({value,label,inverted=false}:{value:string;label:string;inverted?:boolean}){return <View style={styles.metric}><Text style={[styles.metricValue,inverted&&styles.metricValueDark]}>{value}</Text><Text style={[styles.metricLabel,inverted&&styles.metricLabelDark]}>{label}</Text></View>}; function Quick({icon,title,href}:{icon:any;title:string;href:any}){return <Link href={href} asChild><Pressable style={styles.quick}><Icon name={icon} color={palette.red}/><Text style={styles.quickText}>{title}</Text></Pressable></Link>}; function Message({text}:{text:string}){return <View style={styles.message}><Icon name="information-circle-outline" color={palette.amber}/><Text style={styles.messageText}>{text}</Text></View>};
const styles=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center'},scroll:{padding:20,gap:16,paddingBottom:30,alignSelf:'center',width:'100%',maxWidth:720},greeting:{fontSize:31,fontWeight:'800',color:palette.ink,marginTop:4},subtitle:{fontSize:15,color:palette.muted,lineHeight:22},shift:{backgroundColor:palette.black,borderRadius:radius.lg,padding:20,gap:15},shiftTitle:{color:'#fff',fontSize:19,fontWeight:'800'},metrics:{flexDirection:'row',gap:18},metric:{gap:4,flex:1,minWidth:0},metricValue:{color:'#fff',fontSize:25,fontWeight:'800'},metricValueDark:{color:palette.ink},metricLabel:{color:'#C9C4BE',fontSize:13},metricLabelDark:{color:palette.muted},shiftHint:{color:'#C9C4BE',fontSize:13,lineHeight:19},section:{fontSize:21,fontWeight:'800',color:palette.ink},next:{gap:10},loading:{minHeight:130,alignItems:'center',justifyContent:'center',gap:12},empty:{borderWidth:1.5,borderColor:palette.line,borderRadius:radius.lg,padding:22,alignItems:'center',gap:7},emptyTitle:{fontSize:18,fontWeight:'800',color:palette.ink},emptyText:{textAlign:'center',color:palette.muted,lineHeight:20},quickRow:{flexDirection:'row',gap:10},quick:{flex:1,minHeight:105,borderWidth:1.5,borderColor:palette.line,borderRadius:radius.md,padding:14,gap:9,justifyContent:'center'},quickText:{fontSize:14,fontWeight:'800',color:palette.ink},message:{backgroundColor:palette.amberSoft,borderRadius:14,padding:13,flexDirection:'row',gap:8,alignItems:'center'},messageText:{flex:1,color:palette.amber,fontSize:14,fontWeight:'700'},gpsRequest:{borderWidth:1.5,borderColor:palette.line,backgroundColor:palette.surface,borderRadius:radius.md,padding:15,flexDirection:'row',alignItems:'center',gap:10},gpsRequestTitle:{fontWeight:'800',color:palette.ink,fontSize:16},gpsRequestText:{color:palette.muted,fontSize:13,marginTop:3},supervisorMetrics:{flexDirection:'row',gap:8},advisor:{borderWidth:1.5,borderColor:palette.line,backgroundColor:palette.surface,borderRadius:radius.md,padding:13,flexDirection:'row',alignItems:'center',gap:10},advisorAvatar:{height:42,width:42,borderRadius:14,backgroundColor:palette.black,alignItems:'center',justifyContent:'center'},advisorInitial:{fontSize:13,fontWeight:'800',color:'#fff'},advisorName:{color:palette.ink,fontSize:16,fontWeight:'800'},advisorDetail:{color:palette.muted,fontSize:13,marginTop:3},planRoute:{color:palette.red,fontSize:12,fontWeight:'900',marginTop:5},locationState:{paddingHorizontal:8,paddingVertical:5,borderRadius:10,flexShrink:0},locationReported:{backgroundColor:palette.greenSoft},locationMissing:{backgroundColor:palette.soft},locationStateText:{fontSize:11,fontWeight:'800',color:palette.ink},disclaimer:{fontSize:12,lineHeight:18,color:palette.muted,backgroundColor:palette.soft,padding:13,borderRadius:12} });
