import { useState } from 'react';
import { Link } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import type { Client } from '@/features/field/data';
import { AppHeader, Icon, Page } from '@/features/field/ui';
import { useFieldSession } from '@/features/field/session';
import { api } from '@/services/api';
import { palette, radius } from '@/theme/tokens';
export default function SearchScreen(){const {token,selectedPortfolio}=useFieldSession();const [query,setQuery]=useState('');const [items,setItems]=useState<Client[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const search=async()=>{if(!token||!selectedPortfolio||query.trim().length<2)return;setLoading(true);setError('');try{setItems((await api.clients(token,selectedPortfolio.id_table,query)).items);}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible consultar.');}finally{setLoading(false);}};return <Page><AppHeader/><ScrollView contentContainerStyle={styles.scroll}><Text style={styles.title}>Consultar cliente</Text><Text style={styles.subtitle}>Busca solo dentro de tus carteras asignadas.</Text><View style={styles.input}><Icon name="search-outline"/><TextInput value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder="DNI, identificador o nombre" style={styles.textInput}/><Pressable onPress={search}><Icon name="arrow-forward-circle" color={palette.red} size={29}/></Pressable></View>{loading?<ActivityIndicator color={palette.red}/>:null}{error?<Text style={styles.error}>{error}</Text>:null}{query.length>0&&!loading?<Text style={styles.count}>{items.length} resultados</Text>:null}{items.map(item=><Link key={item.identifier} href={{pathname:'/client/[id]',params:{id:item.identifier,idTable:item.portfolio.idTable}}} asChild><Pressable style={styles.card}><Text style={styles.name}>{item.name}</Text><Text style={styles.doc}>{item.document||item.identifier}</Text><Text style={styles.portfolio}>{item.portfolio.name}</Text></Pressable></Link>)}</ScrollView></Page>}
const styles=StyleSheet.create({scroll:{padding:20,gap:14},title:{fontSize:30,fontWeight:'800',color:palette.ink},subtitle:{fontSize:16,color:palette.muted},input:{height:60,borderWidth:1.5,borderColor:palette.ink,borderRadius:18,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:9},textInput:{flex:1,fontSize:16,color:palette.ink},count:{fontWeight:'800',fontSize:17,color:palette.ink},card:{borderWidth:1.5,borderColor:palette.line,borderRadius:radius.md,padding:16,gap:5},name:{fontSize:18,fontWeight:'800',color:palette.ink},doc:{color:palette.muted},portfolio:{color:palette.red,fontWeight:'700',fontSize:13},error:{backgroundColor:palette.amberSoft,color:palette.amber,borderRadius:12,padding:12,fontWeight:'700'} });
